### ISSUE TITLE
Wont compile on MacOS 10.14

### ISSUE THREAD

**Issue by cerberuscgn** [YiannisBourkelis/Andama-Remote-Desktop#40]
Hi all, I tried to compile the AndamaProxy as well as the client. I am failing with one of these error messages:

mousekeyb/MouseMac.cpp:44:24: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef event = CGEventCreateMouseEvent(NULL, kCGEventMouseMoved, CGPointMake(x, y), 0 /*ignored*/);
                       ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57:33: note: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^
mousekeyb/MouseMac.cpp:68:24: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef event = CGEventCreateMouseEvent(NULL, eventType, CGPointMake(mousePos.x(), mousePos.y()), 0 /*ignored*/);
                       ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57:33: note: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^
mousekeyb/MouseMac.cpp:84:24: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef event = CGEventCreateMouseEvent(NULL, eventType, CGPointMake(mousePos.x(), mousePos.y()), 0 /*ignored*/);
                       ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57:33: note: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^
mousekeyb/MouseMac.cpp:101:29: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef eventPress = CGEventCreateMouseEvent(NULL, eventTypeMouseDown, CGPointMake(mousePos.x(), mousePos.y()), 0 /*ignored*/);
                            ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57:33: note: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^
mousekeyb/MouseMac.cpp:104:31: error: no matching function for call to 'CGEventCreateMouseEvent'
    CGEventRef eventRelease = CGEventCreateMouseEvent(NULL, eventTypeMouseUp, CGPointMake(mousePos.x(), mousePos.y()), 0 /*ignored*/);
                              ^~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk/System/Library/Frameworks/CoreGraphics.framework/Headers/CGEvent.h:57:33: note: candidate function not viable: no known conversion from 'int' to 'CGMouseButton' for 4th argument
CG_EXTERN CGEventRef __nullable CGEventCreateMouseEvent(
                                ^

**Comment by cerberuscgn** [comment]
Update: I am now using the development branch, that compiles almost fine.
